### ISSUE TITLE
Extension removed from chrome store and issue with remembering extension settings

### ISSUE THREAD

**Issue by keatit71** [sawyerpollard/MineWeather#29] opened 2021-10-08 22:06 UTC
The worst thing is that this extension has been removed for violating something with chrome web store so people won't be able to get it anymore and secondary to that is i've been having issues with the extension forgetting I chose Celsius seemingly at random.

**Comment by keatit71** [comment] 2021-10-08 22:31
You could always have the extension downloadable on GitHub to be sidoaded for chrome.

You could use textures similar to Minecraft like faithful resource pack if you get permission from the faithful team.

Another option might be to have it as a website people can set to open on new page.

PS extension sometimes forgets my preferences as well

**Comment by vanjmali** [comment] 2021-10-09 12:20
I can confirm that it is not remembering the selected values. When restarting the browser at random times it will just reset the option.

**Comment by keatit71** [comment] 2021-10-09 17:40
Yeah its been doing it before days ago

**Comment by keatit71** [comment] 2021-10-09 19:16
It goes back to Fahrenheit thought it was a default

**Comment by vulpesfelix** [comment] 2021-10-10 21:07
Firefox user here, the extension is still available in the addons store, but it's still on 0.1.0
Still no problems with preferences tho

**Comment by vulpesfelix** [comment] 2021-10-10 21:26
> 
> 
> Maybe just a chrome issue then

or most probably a problem caused by the new update. It's still not on Firefox so I can't say if it's just Chrome or not.

**Comment by sawyerpollard** [comment] 2021-10-11 04:34
> > Maybe just a chrome issue then
> 
> or most probably a problem caused by the new update. It's still not on Firefox so I can't say if it's just Chrome or not.

I believe I may have fixed it. Check out v0.2.1 on the GitHub releases section.

**Comment by GreatSymphonia** [comment] 2021-10-15 15:46
Using a modified texture pack could not solve the problem?

**Comment by sawyerpollard** [comment] 2021-12-21 21:23
I uploaded a new version to the Chrome Store which was approved! So I suppose I can close this issue. I may have fixed the issue with remembering extension settings I hope. But we can create a new issue if it persists in the new version.

Here's the link: https://chrome.google.com/webstore/detail/mineweather/gklgaaagldobfcacmhhbnbgofohfgneb

**Closed by sawyerpollard** 2021-12-21 21:23 UTC
